export const LANDING = '/'
export const HOME = '/home'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/login'
export const SIGN_OUT = '/logoff'
export const PASSWORD_FORGET = '/forgot'
// export const ACCOUNT = '/account'
// export const ADMIN = '/admin'
